### PR TITLE
Publish from GitHub Actions

### PR DESCRIPTION
**Pull request by hiroyuki-sato**

### CODE REVIEW

**Review by dmikurube — APPROVED** [review]
LGTM!

**Comment by dmikurube** [comment]
Ah, but note that the vars and secrets are not yet set.

**Comment by hiroyuki-sato** [comment]
Thanks. I'll create dependabot PR later. I'll wait to set those parameters

**Comment by dmikurube** [comment]
All set.

**Comment by hiroyuki-sato** [comment]
Thanks!

**Pull request merged**
